import {
  MdAddLocation,
  MdEditLocation,
  MdEmojiFlags,
  MdExplore,
  MdFlag,
  MdFlagCircle,
  MdLanguage,
  MdLocationCity,
  MdLocationOff,
  MdLocationOn,
  MdLocationPin,
  MdMap,
  MdMyLocation,
  MdOutlinedFlag,
  MdPinDrop,
  MdPlace,
  MdPublic,
  MdPublicOff,
  MdShareLocation,
  MdSignLanguage,
  MdTravelExplore,
  MdWhereToVote,
  MdAgriculture,
  MdAirportShuttle,
  MdDeliveryDining,
  MdDirectionsBike,
  MdDirectionsCar,
  MdElectricRickshaw,
  MdFireTruck,
  MdLocalShipping,
  MdRvHookup,
  MdTwoWheeler,
} from 'react-icons/md'

/** Material icon keys — keep in sync with rider-api/src/shared/material-icon-catalog.js */
export const MATERIAL_ICON_COMPONENTS = {
  two_wheeler: MdTwoWheeler,
  electric_rickshaw: MdElectricRickshaw,
  directions_car: MdDirectionsCar,
  local_shipping: MdLocalShipping,
  fire_truck: MdFireTruck,
  rv_hookup: MdRvHookup,
  agriculture: MdAgriculture,
  airport_shuttle: MdAirportShuttle,
  directions_bike: MdDirectionsBike,
  delivery_dining: MdDeliveryDining,
  public: MdPublic,
  public_off: MdPublicOff,
  language: MdLanguage,
  sign_language: MdSignLanguage,
  flag: MdFlag,
  outlined_flag: MdOutlinedFlag,
  flag_circle: MdFlagCircle,
  emoji_flags: MdEmojiFlags,
  travel_explore: MdTravelExplore,
  explore: MdExplore,
  location_on: MdLocationOn,
  location_off: MdLocationOff,
  location_city: MdLocationCity,
  location_pin: MdLocationPin,
  place: MdPlace,
  pin_drop: MdPinDrop,
  map: MdMap,
  my_location: MdMyLocation,
  share_location: MdShareLocation,
  add_location: MdAddLocation,
  edit_location: MdEditLocation,
  where_to_vote: MdWhereToVote,
}

export function MaterialIcon({ iconKey, className = 'text-lg', title }) {
  const Icon = MATERIAL_ICON_COMPONENTS[iconKey]
  if (!Icon) return <span className={className}>?</span>
  return <Icon className={className} title={title} aria-hidden={title ? undefined : true} />
}
